version: "3.8"

#rabbitmq
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    container_name: some-rabbit
    ports:
      - "8080:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

#service a
  service-a:
    build: ./service_a
    ports:
      - "8000:8000" #http://localhost:8000/docs
    depends_on:
      - rabbitmq
    volumes:
      - ./service_a:/app

#service b
  service-b-api:
    build: ./service_b      
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000" #http://localhost:8001/docs
    environment:
      - RABBIT_HOST=rabbitmq 
    depends_on:
      rabbitmq:
        condition: service_healthy

#service b worker
  service-b-worker:
    build: ./service_b
    command: python worker.py
    deploy:
      replicas: 2
    environment:
      - RABBIT_HOST=rabbitmq
      - SERVICE_A_URL=http://service-a:8000/results
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-a:
        condition: service_started